- name: nginx install and start
  hosts: catalogue
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
