- name: play level variables
  hosts: local
  connection: local
  vars:
    course: ansible
    tutor: siva
    from_place: "play level"
  tasks:
  - name: var test
    ansible.builtin.debug:
      msg: "Course is: {{ course }} and instructor is {{ tutor }} from {{ from_place }}"
