- name: task level variables
  hosts: local
  connection: local
  vars:
    course: ansible
    tutor: siva
    from_place: "play level"
  tasks:
  - name: var test
    vars:
      course: devops
      tutor: cloud siva
      from_place: "task level"
    ansible.builtin.debug:
      msg: "Course is: {{ course }} and instructor is {{ tutor }}, from {{ from_place }}"
