- name: arguments variables
  hosts: local
  connection: local
  tasks:
    - name: var test
      ansible.builtin.debug:
       msg: "Course is: {{ course }} and instructor is {{ tutor }}, vars from {{ from_place }}"


# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 -e "course=Devops" -e "tutor=siva" -e "from_place=args" 09-vars_args.yaml