- name: Check facts
  hosts: local
  connection: local
  tasks:
  - name: Checking  facts
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Checking  facts
    ansible.builtin.apt:
      name: nginx
      state: latest
    when: ansible_os_family == "Debian"
