- name: Multipackage install using loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Installing Packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - python3
    - docker
    - jq